/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {


            //create an instanse of resturant class
            Restaurant restaurant = new Restaurant("aldaiaa restaurant",3,5);
            System.out.println(restaurant);


            //craete an instanse of review class
           Review review = new Review("nice rastaurant","sanabel",4);
           Review review2 = new Review("good rastaurant","meme",6);
           Review review3 = new Review("Ilove rastaurant","ali",3);

           restaurant.addReview(review);
           restaurant.addReview(review2);
           restaurant.addReview(review3);

           System.out.println(restaurant.getReviews());

           System.out.println(review);
           System.out.println(review2);
           System.out.println(review3);




    }
}
