/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    //test for resturant  constructor
    @Test public void testConstructorRestaurant(){
        Restaurant test =new Restaurant("aldaiaa" ,3,5);
        assertEquals("aldaiaa" ,test.getName());
        assertEquals( 3,test.getNumStars());
        assertEquals(5 ,test.getPriceCategory());
    }
    //test for review  constructor
    @Test public void testConstructorReview(){
        Review test =new Review("goodRestaurant" ,"sanabel",5);
        assertEquals("goodRestaurant" ,test.getBody());
        assertEquals("sanabel" ,test.getAuthor());
        assertEquals( 5,test.getNumStars());
    }
        @Test public void testRestaurantToString(){
        Restaurant test =new Restaurant("aldaiaa" ,3,5);
//        test.toString();
        assertEquals("Restaurant{name='aldaiaa', numStars=3, priceCategory=5}",test.toString());

    }
    @Test public void testReviewToString(){
        Review test =new Review("good resturant" ,"sanabel",5);
        assertEquals("Review{author='sanabel', numStars=5, body='good resturant'}",test.toString());
    }
      @Test public void testAddReview(){
//        Restaurant restaurant = new Restaurant("aldaiaa",3,5);
        Review test =new Review("good resturant" ,"sanabel",5);
//        restaurant.addReview(test);
        assertEquals("Review{author='sanabel', numStars=5, body='good resturant'}",test.toString());

    }

    // test for shop constructor
    @Test public void testShopConstructor(){
        Shop shop1 = new Shop("mecca mall","multibule uses",5);
        assertEquals("mecca mall" ,shop1.getName());
        assertEquals("multibule uses" ,shop1.getDescription());
        assertEquals( 5,shop1.getNumOfDollarSigns());
    }

    @Test public void testShopToString(){
        Shop shop1 = new Shop("mecca mall","multibule uses",5);
        assertEquals("Shop{name='mecca mall', description='multibule uses', numOfDollarSigns=5}",shop1.toString());
    }
    @Test public void testShopAddReview(){
        Shop shop1 = new Shop("mecca mall","multibule uses",5);
        assertEquals("Shop{name='mecca mall', description='multibule uses', numOfDollarSigns=5}",shop1.toString());

    }


    //test for theater constructor
    @Test public void testTheaterConstructor(){
        Theater theater = new Theater("sanabel");
        assertEquals("sanabel" ,theater.getName());
    }
@Test public void testTheaterToString(){
    Theater theater = new Theater("sanabel");
   assertEquals("Theater{name='sanabel', movies='[]'}",theater.toString());
}
@Test public void testAddRev(){
    Theater theater = new Theater("sanabel");
    theater.addRev("good","sanabel",4);
    theater.getMovies();
    assertEquals("Theater{name='sanabel', movies='[]'}",theater.toString());
}
@Test public void testAddedMovie(){
    Theater theater = new Theater("test");
    theater.addMovie("sssssss");
    theater.addMovie("ttttttt");
    assertEquals("Theater{name='test', movies='[sssssss, ttttttt]'}", theater.toString());

}


}




