/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testEmpty() throws IOException {
        Path path = Paths.get("C:\\Users\\TLCAT-1220\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        assertEquals(0,App.lenterJS(path.toString()));
    }
    @Test void testNoError() throws IOException {
        Path path = Paths.get("C:\\Users\\TLCAT-1220\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        assertEquals(0,App.lenterJS(path.toString()));
    }
    @Test void testOneError() throws IOException {
        Path path = Paths.get("C:\\Users\\TLCAT-1220\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        assertEquals(1,App.lenterJS(path.toString()));
    }
    @Test void testThreeError() throws IOException {
        Path path = Paths.get("C:\\Users\\TLCAT-1220\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        assertEquals(3,App.lenterJS(path.toString()));
    }
    @Test void testManyErrors() throws IOException {
        Path path = Paths.get("C:\\Users\\TLCAT-1220\\401\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        assertEquals(4,App.lenterJS(path.toString()));
    }
}
