/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
@Test public void testThreeError(){
    String testPath = "./src/test/resources/testManyError.js";
    ArrayList<String> test = new ArrayList<String>();
    test.add("Line 3 : Missing semicolon.");
    test.add("Line 4 : Missing semicolon.");
    test.add("Line 12 : Missing semicolon.");
    assertEquals( "[Line 3 : Missing semicolon., Line 4 : Missing semicolon., Line 12 : Missing semicolon.]" ,test.toString());
}
@Test public void testNoError(){
    String testPath = "./src/test/resources/testNoError.js";
    ArrayList<String> outList = new ArrayList<String>();
    assertEquals( "[]" , outList.toString());
}
    @Test public void testOneError(){
        String testPath = "./src/test/resources/testOneError.js";
        ArrayList<String> outList = new ArrayList<String>();
        outList.add("Line 1 : Missing semicolon.");
        assertEquals( "[Line 1 : Missing semicolon.]" , outList.toString());
    }
@Test public void testManyError(){
    String testPath = "./src/test/resources/testManyError.js";
    ArrayList<String> test = new ArrayList<String>();
    test.add("Line 3 : Missing semicolon.");
    test.add("Line 4 : Missing semicolon.");
    test.add("Line 12 : Missing semicolon.");
    test.add("Line 13 : Missing semicolon.");
    test.add("Line 17 : Missing semicolon.");
    test.add("Line 20 : Missing semicolon.");
    test.add("Line 22 : Missing semicolon.");
    test.add("Line 24 : Missing semicolon.");

    assertEquals( "[Line 3 : Missing semicolon., Line 4 : Missing semicolon., Line 12 : Missing semicolon., Line 13 : Missing semicolon., Line 17 : Missing semicolon., Line 20 : Missing semicolon., Line 22 : Missing semicolon., Line 24 : Missing semicolon.]" ,test.toString());
}

}

